baseurl = "http://yourSiteHere"
languageCode = "ru"
title = "Сонейка"

[params]
    description = "Наука, история, творчество. Блог для людей с широким кругозором"
    theme = "theme-base-08"

[taxonomies]
    tag = "tags"
    category = "categories"
